name             'chef-docker-stuff'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-docker-stuff'
long_description 'Installs/Configures chef-docker-stuff'
version          '0.1.0'
depends 'docker', '~> 2.0'
depends 'apt'
